engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:  
     enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.md"
exclude_paths:
- "**.min.*"
- */**/dist/**/*
- build/**/*
- release/**/*
ecmaFeatures:
  modules: true
  jsx: true

env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true
